default: &default
  adapter: postgresql
  encoding: unicode
  username: chris
  password: 1234
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_blog
  host: 'localhost'

test:
  <<: *default
  database: rails_blog

production:
  <<: *default
  database: rails_blog
  username: chris
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
